### ISSUE TITLE
Find and Fix Regex Pattern

### ISSUE THREAD

**Issue by kphan32** [GTBitsOfGood/bgc-safety-f2021#10]
### Description
It was reported that a Regex pattern in the application was producing errors. Find the offending pattern and fix it.
### Acceptance Criteria
* All Regex patterns in the application function correctly within their context.
### User Story
* As a user, I should not see Regex errors
### Story Points
* 2 - one day of work

**Comment by matthewbrown77** [comment]
@kphan32 Is this issue referring to [this issue](https://github.com/GTBitsOfGood/bgc-safety/issues/104) detailed in the old repo or is this a separate problem? I only see 1 regex instance in the app used for email validation.

**Comment by kphan32** [comment]
@matthewbrown77 yes that seems like the one.
