### ISSUE TITLE
Change Bus Driver Landing Page to Route Selection

### ISSUE THREAD

**Issue by kphan32** [GTBitsOfGood/bgc-safety-f2021#37]
### Description

Bus drivers should be redirected to the route selection page after signing in.

### Acceptance Criteria

Bus drivers are redirected to the route selection page after signing in.

### User Story

As a bus driver, I should be redirected to the route selection page after signing in.

### Story Points
* 1 - couple of lines to fix

**Comment by iwiw17** [comment]
Looks like ticket above with Madeline's PR will solve this - double-check and close.
