### ISSUE TITLE
Sign-in Redirects to localhost

### ISSUE THREAD

**Issue by iwiw17** [GTBitsOfGood/bgc-safety-f2021#4]
### Description
When signing in, the application redirects the user to a `localhost` URL. Note that this issue does not occur in local dev environments.
### Acceptance Criteria
* The call back URL matches the application URL.
### User Story
* As a user, I should be redirected to the application when signing in.
### Story Points
* 1 - couple of lines to fix

**Comment by kphan32** [comment]
This issue was caused by Auth0 not having the correct callback URL for Vercel deployments. Fixed.
